config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :movements
  devise_for :users

  root 'accounts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    
  end
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  name       :string
#  date_from  :date
#  date_to    :date
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Account < ApplicationRecord
  belongs_to :user
  has_many :movements
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movement.rb
# == Schema Information
#
# Table name: movements
#
#  id          :integer          not null, primary key
#  type        :boolean
#  amount      :integer
#  description :string
#  date        :datetime
#  account_id  :integer          not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Movement < ApplicationRecord
  belongs_to :account
  belongs_to :user

  validates :amount, :description, :date, :account_id, presence: :true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all.where(user_id: current_user.id)
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    
    @account = Account.new(account_params)
    @account.user_id = current_user.id
    
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, index: "Account was successfully created." }
        format.json { render :index, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :date_from, :date_to, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale
    before_action :authenticate_user!



    def set_locale
        I18n.locale = 'es'
    end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_movement, only: %i[ show edit update destroy ]

  # GET /movements or /movements.json
  def index
    @movements = Movement.all.where(user_id: current_user.id)
  end

  # GET /movements/1 or /movements/1.json
  def show
  end

  # GET /movements/new
  def new
    @movement = Movement.new
  end

  # GET /movements/1/edit
  def edit
  end
  def type_movement

  end
  #= f.input :type, as: :select, collection: 
  # POST /movements or /movements.json
  def create
    @movement = Movement.new(movement_params)
    @movement.user_id = current_user.id
    @types = {"debito" =>false, "credito" => true}
    #Intentando registrar el tipo
    #@movement.type = @movement if @movement.amount > 0 then @types["credito"] else @types["debito"] end
    # pry
    respond_to do |format|
      if @movement.save
        format.html { redirect_to @movement, notice: "Movement was successfully created." }
        format.json { render :show, status: :created, location: @movement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movements/1 or /movements/1.json
  def update
    respond_to do |format|
      if @movement.update(movement_params)
        format.html { redirect_to @movement, notice: "Movement was successfully updated." }
        format.json { render :show, status: :ok, location: @movement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movements/1 or /movements/1.json
  def destroy
    @movement.destroy
    respond_to do |format|
      format.html { redirect_to movements_url, notice: "Movement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movement = Movement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movement_params
      params.require(:movement).permit(:type, :amount, :description, :date, :account_id, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/views/accounts/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@account) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: "Nombre" 
    = f.input :date_from, label: "Fecha de creación" 
    = f.input :date_to, label: "Fecha de expiración" 

  .form-actions
    = button_tag 'Submit', type: 'submit', class: "btn btn-success"

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Lista de Cuentas 

%table{:class => "table table-striped"}
  %thead
    %tr
      %th Nombre
      %th Fecha de creación
      %th Fecha de expiración
      %th
      %th
      %th

  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.name
        %td= account.date_from
        %td= account.date_to
        %td= link_to 'Show', account
        %td= link_to 'Edit', edit_account_path(account)
        %td= link_to 'Destroy', account, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Crear cuenta', new_account_path, class: "btn btn-success"

app/views/accounts/new.html.haml
%h1 Nueva cuenta

= render 'form'

= link_to 'Atrás', accounts_path, class: "btn btn-secondary"

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @account.name
%p
  %b Date from:
  = @account.date_from
%p
  %b Date to:
  = @account.date_to
%p
  %b User:
  = @account.user

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">My admin</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/movements">Movimientos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/accounts">Cuentas</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %>
        </li>
      </ul>
      <span class="navbar-text">
        Usuario: <%= current_user[:email] if !current_user.blank?%>
      </span>
    </div>
  </nav>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProg3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
  </head>
  <nav>
    <%= render "layouts/nav" %>
  </nav>
  <body>

    <br>
    <br>
    <%= yield %>
  </body>
</html>

app/views/movements/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@movement) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  #form-inputs.form-group
    = f.input :amount, label: "Monto" 
    = f.input :description, label: "Descripción" 
    = f.input :date, input_html: { class: 'datepicker' }, label: "Fecha de realización" 
    = f.association :account,  label: "Cuenta del movimiento", as: :select, collection: Account.where("date_to >= ?", Time.now)

  .form-actions
    = button_tag 'Submit', type: 'submit', class: "btn btn-success"

app/views/movements/edit.html.haml
%h1 Editing movement

= render 'form'

= link_to 'Show', @movement
\|
= link_to 'Back', movements_path

app/views/movements/index.html.haml
%h1 Movimientos de cuenta

%table{:class => "table table-striped"}
  %thead
    %tr
      %th Monto
      %th Descripción
      %th Fecha
      %th Cuenta
      %th
      %th
      %th

  %tbody
    - @movements.each do |movement|
      %tr
        %td= movement.amount
        %td= movement.description
        %td= movement.date
        %td= movement.account.name
        %td= link_to 'Ver', movement
        %td= link_to 'Editar', edit_movement_path(movement)
        %td= link_to 'Eliminar', movement, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Generar movimieento', new_movement_path, class: "btn btn-success"

app/views/movements/new.html.haml
%h1 Nuevo movimiento

= render 'form'

= link_to 'Atrás', movements_path, class: "btn btn-secondary"

app/views/movements/show.html.haml
%p#notice= notice

%p
  %b Type:
  = @movement.type
%p
  %b Amount:
  = @movement.amount
%p
  %b Description:
  = @movement.description
%p
  %b Date:
  = @movement.date
%p
  %b Account:
  = @movement.account
%p
  %b User:
  = @movement.user

= link_to 'Edit', edit_movement_path(@movement)
\|
= link_to 'Back', movements_path